"""Changed password and email size

Revision ID: 4deea68a57b2
Revises: 00a6d94b3e02
Create Date: 2025-09-27 16:07:17.741663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4deea68a57b2'
down_revision: Union[str, None] = '00a6d94b3e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)
    # ### end Alembic commands ###
